name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make USER_FLAGS="-s -O3"

    - uses: actions/upload-artifact@v4
      with:
        name: def2fgd2ent Linux
        path: bin/
        if-no-files-found: error

  windows:

    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
    - uses: actions/checkout@v4
    - name: make
      run: make USER_FLAGS="-s -O3 -static"

    - uses: actions/upload-artifact@v4
      with:
        name: def2fgd2ent Windows
        path: bin/
        if-no-files-found: error

